sudo: required
services:
  - docker

before_install:
  - docker build -t thomashuan88/docker-react -f Dockerfile.dev .

script:
  - docker run thomashuan88/docker-react npm run test -- --coverage